CREATE DATABASE fratinfo;

USE fratinfo;

CREATE TABLE house_info (
	name varchar(50) NOT NULL PRIMARY KEY,
	description varchar(2000) NOT NULL,
	chapter varchar(50) NOT NULL,
	members int(4),
	cover_image varchar(150),
	profile_image varchar(150), /*Should be not null*/
	calendar_image varchar(150), /*Should be not null*/
	preview_image varchar(150),
	address varchar(200)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO house_info(name, description, chapter, members, cover_image, profile_image, calendar_image, preview_image, address)
	VALUES
	('Acacia', 'Since its founding in 1949, Acacia has been an active member of the Rensselaer fraternity system and has taken an active part of the Troy, NY community in which it resides. Our house is located on Sunset Terrace behind BAR-H and RAHPS.\n\nBe sure to check our rush calendar to see if there are any events you might be interested in attending. You are always welcome to come by the house for some dinner (every school night, 6:00 PM) or just to hang out.\n\nBeing a part of a fraternity is a lot more than just living together in a house; it is learning to deal with different types of people, learning responsibility for your actions, having friends to help you through difficulties, and most importantly forming ties with friends that will last a lifetime.\n\nEach member of Acacia is an individual with their own style, goals, knowledge, and background. Each member of Acacia pursues their own path after graduation. But, each member of Acacia strives to live up to the Preamble to the Laws of Acacia in his own way:\n\nWe, students, faculty, and alumni of various universities and colleges, do hereby adopt this Constitution; to strengthen the ties of friendship, one with another; to prepare ourselves as educated men, to take a more active part and to have a greater influence in the affairs of the community in which we may reside; and, above all, to seek the truth and knowing it, to give light to those with whom we may be associated as we travel along life''s pathway.', 'RPI', NULL, NULL, NULL, NULL, NULL, '145 Sunset Terrace Troy NY 12180'),
	('Alpha Chi Rho', 'Alpha Chi Rho is a men’s collegiate fraternity that is looking to help shape college students into men of value in our community.  This is being achieved through the guidance of our four national landmarks:\n\n1. Membership among those who are prepared to realize in word and deed the Brotherhood of all men.\n2. The persistence of a high and clean moral standard.\n3. The paramount duty of Brotherly love among members.\n4. Judgment by not by externals but by intrinsic worth; no one is denied membership into Alpha Chi Rho because of race, creed, or nationality.\n\nFor the Delta Phi Chapter of Alpha Chi Rho, the past year has been an exciting and fulfilling experience. As a house we have helped paint a local church and raised money for Relay For Life. We also held a free Jazz concert in our backyard. Neighbors and fellow students enjoyed a barbeque while listening to one of RPI''s finest jazz ensembles. Overall, Alpha Chi Rho is a fraternity that helps build a man''s character as well as pushes college students to reach their upmost potential.', 'Delta Phi', NULL, NULL, NULL, NULL, NULL, '1621 Tibbits Ave Troy NY 12180'),
	('Alpha Epsilon Pi', 'Alpha Epsilon Pi is a diverse fraternity with a Jewish background. Rho Pi promotes leadership, faith, academic excellence and success in all aspects of life. Our fraternity establishes brotherhood through friendship, fun, security and support.\n\nIt’s about having the opportunity to mature amongst some of the greatest friends you’ll ever make. It doesn’t matter where you come from, what your major is or where you want to go in life – we’re always looking out for one another.', 'Rho Pi', NULL, NULL, NULL, NULL, NULL, '145 Sunset Terrace Troy NY 12180'),
	('Alpha Phi Alpha', 'The Untouchable Omicron Upsilon Chapter of Alpha Phi Alpha Fraternity, Inc. seated at Rensselaer Polytechnic Institute would like to personally welcome and thank you for visiting our chapter website. Alpha Phi Alpha is strongly committed to the enhancement of Rensselaer Polytechnic Institute and we are truly dedicated to uplifting our community.\n\nSince 1983, with the inception of Alpha Phi Alpha Fraternity, Incorporated here at Rensselaer, we have been steadfast in serving all. Omicron Upsilon has been an agent advocating for change, economically, politically, and socially, at Rensselaer. Through our workshops, programs, and events, we continue to be the juggernaut in providing a myriad of services that empower multicultural students and the entire community. "First of all, servants of all, we shall transcend all" is our motto and the cornerstone of our organization.\n\nToday, Omicron Upsilon stands prepared to provide the necessary tools, resources, and skills to address our community needs in order to survive on the college campus and within our local communities. May this message serve as the ambassador in our form of appreciation to you. Your continued support and contributions allow this organization to continue marching onward and upward towards the light.', 'Omicron Upsilon', NULL, NULL, NULL, NULL, NULL, NULL),
	/*('Alpha Phi Omega', 'Placeholder Description', 'Chi Chi', NULL, NULL, NULL, NULL, NULL, '123 drive troy ny'),*/
	('Alpha Sigma Phi', 'Alpha Sigma Phi is a fraternity founded upon the values of Silence, Charity, Purity, Honor, and Patriotism. We hold these values closely as we strive to achieve our ultimate purpose, To Better The Man. We achieve this goal in a multitude of ways, ranging from regular brotherhood unity events, philanthropic efforts, social occasions, professional development events, and encouraging everyone to strive for leadership positions within the chapter. In this house, brothers of various majors and backgrounds come together to better themselves educationally, socially, and fraternally. The end result is not only a group of friends, but a close brotherhood and genuine bond that can only be found at 16 Belle Ave. Lastly, the best way to get to know any organization like us is to meet its members. We are always hanging around or doing something fun so come through and see what we mean.', 'Beta Psi', NULL, NULL, NULL, NULL, NULL, '16 Belle Ave Troy NY 12180'),
	('Chi Phi', 'The Theta Chapter of the Chi Phi Fraternity was founded on May 25, 1878. Chi Phi is the oldest social fraternity in America and the Theta Chapter boasts notable alumnus such as George Ferris and Frank and Kenneth Osborn. Their house is located across from Quad, on the corner of 15th St. and Sage Avenue.\nThe brothers of Chi Phi utilize a strong network of alumni who visit and provide aid in academic and professional careers. The brothers of the Theta Chapter of Chi Phi are very diverse in both interests and cultural backgrounds.\nThe Theta Chapter is heavily involved in Chi Phi’s national philanthropy, the Boys and Girls Club of America. Theta assist the Boys and Girls Club by tutoring and putting on holiday events for the local youth. Every spring, the brothers of the Theta Chapter partner with the St. Baldrick’s Foundation, an organization that raises money to support the research of childhood cancers. Last spring, 26 of the 41 brothers volunteered to shave their heads to raise money for St. Baldrick’s. In total, the chapter raised in excess of $4,300 becoming the largest donor at the local St. Baldrick’s fundraiser.\nChi Phi is a vibrant and diverse fraternity that strives to build True Gentleman though Truth, Honor, and Personal Integrity. The brothers of the Theta Chapter of Chi Phi participate in a variety of activities from varsity and intramural sport, clubs, and leadership positions. Chi Phi is a welcoming environment that that anyone can find a home in.', 'Theta', NULL, NULL, NULL, NULL, NULL, '1981 15th St Troy NY 12180'),
	('Delta Kappa Epsilon', 'The brothers of the Psi Omega chapter of Delta Kappa Epsilon fraternity fully embody the gentleman, the scholar, and the jolly good fellow, the three pillars upon which the entire fraternity was first founded. Refounded at RPI in 2014, DKE is rapidly increasing in size, and has already taken initiative in several leadership positions on and off RPI’s campus. We currently live at 901 Peoples Avenue, Troy N.Y. 12180, which is a short walk from the academic center of campus.\n\nOur fraternity has a strong brotherhood. Together, we go on camping and hiking trips, head out to concerts and movies, play paintball, and take trips out of state to places like Montreal and Myrtle Beach. We’re also constantly doing things at the house, whether that’s grilling and building things out back on our new patio or just hanging out on our newly-renovated chapter floor. Additionally, we compete against many of the clubs and other Greek houses at RPI in intramural sports, like soccer and hockey; and if it’s not in intramural sports, we can be found in clubs all over campus or as teaching assistants for several academic courses.\n\nDKE also participates in a multitude of philanthropy events in its community. This extensive list includes holding fundraisers with other Greek organizations to raise money for charity, participating in Relay for Life, and volunteering at Albany’s Regional Food Bank.\n\nJoining a fraternity is a fully unique experience, unlike any other club or activity that can be found on RPI’s campus. In DKE, brothers have access to a variety of things to do, a support network they can draw on, and real opportunities to shape the brotherhood in ambitious and exciting ways unique to a young organization. DKE gentlemen strive to excel as leaders, scholars, and, of course, brothers in all aspects of life; but, above all else, DKE looks for the very best of men. That is what you will find within DKE.', 'Psi Omega', NULL, NULL, NULL, NULL, NULL, ' 901 Peoples Avenue Troy NY 12180'),
	('Delta Phi', 'The Delta Phi has remained a small fraternity. Our small size has granted the Lambda chapter a substantial degree of local autonomy - allowing us to develop our own traditions and policies. We currently reside at 14, 15, and 16 Colvin Circle in the Rensselaer Apartment Housing Projects (RAHPs).\n\nOur bonds as friends and brothers are built upon the diversity of our majors, interests, and hobbies. We place a strong emphasis on academic achievement, and have incorporated programs to help brothers reach their academic goals. The bonds of friendship we build as active brothers carry on in the years after graduation.', 'Lambda', NULL, NULL, NULL, NULL, NULL, '14 Colvin Circle Troy NY 12180'),
	('Delta Tau Delta', 'Delta Tau Delta has been committed to leading lives of excellence at RPI since 1879.  Through the four pillars of Truth, Courage, Faith, and Power our brothers have been able succeed both academically and socially.\n\nThe Upsilon Chapter of Delta Tau Delta  provides a focus on professional development, with an extensive alumni network dedicated to providing programs to maximize the success of undergraduate brothers. Delta Tau Delta partners with the Juvenile Diabetes Research Foundation, to raise money for research and treatment, and engages in numerous other community service activities to benefit the capital region.\n\nHere you will find more than just a house.  You will find a fraternity.  You will find people who will stand with you through all the trials and tribulations of life.  You will find mentors.  You will find leaders.  You will find more than just true friends.  You will find a family.  Here you will find your brothers.', 'Upsilon', NULL, NULL, NULL, NULL, NULL, '133 Sunset Terrace Troy NY 12180'),
	('Lambda Chi Alpha', 'Lambda Chi Alpha is a social fraternity grounded in timeless traditions and ideals. Members strive  to cultivate a supportive and comprehensive brotherhood which gives its men a developmental framework to mature and become men capable of bettering society.\n\nIn 1972, Lambda Chi Alpha abolished pledging. In its place, Lambda Chi Alpha offers the Associate Members Program in which new members are treated as equals with the same rights and rules as every brother. Lambda Chi Alpha promotes equality amongst its members, which fosters a true fraternal brotherhood.', 'Epailon Eta', NULL, NULL, NULL, NULL, NULL, '200 Sunset Terrace Troy NY 12180'),
	('Phi Gamma Delta', 'The brothers of FIJI (our letters are Phi Gamma Delta, but we go by FIJI) are a group of easygoing guys who pride ourselves on abiding by our five core values of Friendship, Knowledge, Service, Morality, and Excellence and who are active in many different parts of campus life.\n\nWe have a bunch of interests ranging from intramural sports like frisbee and soccer to community service including a week of “FIJI Islander” themed fundraising events in the spring.\nOur house in downtown Troy is hard to miss - just look up for the big white steeple!', 'Tau Nu', NULL, NULL, NULL, NULL, NULL, '82 3rd St Troy NY 12180'),
	('Phi Iota Alpha', 'The Alpha Chapter of Phi Iota Alpha Fraternity, Inc.: The Oldest Latino Fraternity in Existence.\n\nPhi Iota Alpha''s mission is to develop leaders and create innovative ways to unite the Latino community.\n\nOur vision is “La Unión De La Patria Latino Americana.” Our brotherhood is composed of university and professional men committed towards the empowerment of the Latin American community.\n\nWe do this by providing social, cultural programs and activities geared towards the appreciation, promotion, and preservation of Latin American culture.', 'Alpha', NULL, NULL, NULL, NULL, NULL, '57 13th St Troy NY 12180'),
	('Phi Kappa Theta', 'At Phi Kappa Theta, we are actively involved in enriching our college experience by exposing ourselves to a variety of people and opportunities. Although we emphasize academics, brothers also participate in intramural sports, music groups, and other campus organizations. Socially, we organize several events each year for RPI students and contribute regularly to our community.\n\nAs brothers of Phi Kappa Theta, we also take great pride in the strength of our brotherhood and seek to improve our lives through a network of support and friendship. We are excited to meet new individuals who will continue to help us achieve these ideals.', 'NY Sigma', NULL, NULL, NULL, NULL, NULL, '107 Sunset Terrace Troy NY 12180'),
	('Phi Mu Delta', 'At Phi Mu Delta, you get the best of what you could possibly get out of a fraternity. We have such varied interests and personalities that we take part in all kinds of activities, like hosting parties, taking part in community service, playing sports, playing video games, and just hanging out. We attract a varied crowd here, because in a lot of ways, we are different than other fraternities, in both what we do and how we view ourselves and one another. Ultimately, despite our differences, we all are brothers who share the values of brotherhood, service and democracy, and anyone who feels the same way would be more than welcome here.', 'Nu Theta', NULL, NULL, NULL, NULL, NULL, '224 Pawling Ave Troy NY 12180'),
	('Phi Sigma Kappa', 'Phi Sigma Kappa is a tight knit group of guys who like to have a good time. Our relatively small size means we forge strong bonds and come to know each other as brothers quickly and easily. Many of us did not envision ourselves in a Fraternity in college, but we all found something special in Phi Sig that drew us in. We have a wide representation of college majors and a devotion (and great track record) for academic excellence and community service. For all of us, joining Phi Sigma Kappa was one of the best decisions of our lives. If you want to enjoy your college years, get to know a fun and committed group of people, and be the best man that you can be, rush Phi Sig! Damn Proud!', 'Gamma Tetaron', NULL, NULL, NULL, NULL, NULL, '316 Congress St Troy NY 12180'),
	('Pi Delta Psi', 'The mission of Pi Delta Psi Fraternity, Inc. is to maintain its Fraternal existence by instilling values that nurture and perpetuate the continual growth and development of the individual through Academic Achievement, Cultural Awareness, Righteousness, Friendship and Loyalty while fostering ethical behavior, leadership, and philanthropy.\n\nPi Delta Psi was founded on these principles to help promote Asian Awareness amongst ourselves and throughout the community. We envisioned this to be possible by going out of the boundaries of an organization and creating a Fraternity on the basis of common goals and ideals in the form of a brotherhood. We believe that through education, we can become more knowledgeable about the different Asian cultures, overcome obstacles of racism and discrimination, therefore unifying us as a whole.\n\nThis mission statement embodies the purpose of our Fraternity and is set forth as a guide that empowers each member to better himself, the Brotherhood, community, and society as a whole.', 'Theta', NULL, NULL, NULL, NULL, NULL, NULL),
	('Pi Kappa Alpha', 'All men were created equal, until 1868. March 1st, 1868 the Pi Kappa Alpha fraternity, better known as PIKE was founded. Since then, it has grown to be one of the largest Greek organizations with over 220 chapters and 275,000 lifetime initiates worldwide. The Gamma Tau chapter at RPI is an organization dedicated to fostering the true ideals of brotherhood within its members. The brothers of Pi Kappa Alpha are committed to helping themselves and each other become true well rounded men for others. These values once instilled in our members allow them to contribute to society and the community in positive ways.The Alpha Males of Pi Kappa Alpha use their superior social, technical, and emotional intelligence to make life better for not only them but those lucky enough to be around them. If you want to be in a frat, look elsewhere. If you want to join a brotherhood, see you at 2228 12th St.', 'Gamma Tau', NULL, NULL, NULL, NULL, NULL, '2228 12th St Troy NY 12180'),
	('Pi Kappa Phi', 'Since 1904, the brothers of Pi Kappa Phi have been building better men on college campuses across the nation. Our chapter, Alpha Tau, was installed on June 13, 1931. The brothers reside in a 19th century mansion located in Downtown Troy, which earned the chapter its nickname “Castle”. Since then, the men of the Alpha Tau chapter have held themselves to the highest standards of CLASS – Character, Leadership, Academics, Sportsmanship, and Service. Pi Kappa Phi is the only fraternity to own and operate its own national philanthropy, The Ability Experience, with the purpose of instilling lifelong service in our members and serving people with disabilities. Since its creation, members have raised nearly $8 million dollars as well as donated thousands of man hours to renovate facilities that serve people with disabilities. Our chapter in particular raises money through philanthropy events such as Haunted House and Pedal for Push. Rushing Pi Kappa Phi promises to be a life changing experience. You will build friendships and relationships that will last a lifetime as well as develop leadership and communication skills that will further your academic career.', 'Alpha Tau', NULL, NULL, NULL, NULL, NULL, '49 2nd St Troy NY 12180'),
	('Pi Lambda Phi', 'Pi Lambda Phi was founded as the nation''s first non-sectarian fraternity in 1895. Our chapter house is located at 300 Pawling Avenue, about two miles south of campus. We are proud to have a diverse brotherhood with many different majors, interests, and hobbies. Popular activities include barbeques and yard games like whiffle ball, volleyball, and football. Our brothers are dedicated to the elimination of prejudice in everyday life.', 'NY Kappa Tau', NULL, NULL, NULL, NULL, NULL, '300 Pawling Ave Troy NY 12180'),
	('Psi Upsilon', 'Psi Upsilon is a small co-ed fraternity located next to BARH at 2140 Burdett Avenue. Currently, we have 20 active brothers and we focus on building strong friendships and being true to yourself. Our friendship and brotherhood are unlike any other.\n\nAs a co-ed fraternity, Psi Upsilon boasts a wide variety of interests among its brothers (everyone is a "brother" regardless of gender). These interests range from board games to anime to arts and music, with each brother having unique interests that we accept wholeheartedly.\n\nWhile Psi-U has the history and ritual of a fraternity, we focus on individual interactions between brothers. We foster friendly and cordial relationships between all of our members, creating a group that is easy to talk to and fun to hang out with. This camaraderie allows us to provide friendly, but effective support to any brother that needs or requests it.\n\nOur fraternity provides a family away from home. We work together and play together, having a good time while we support each other as we make our way through college.', 'Epsilon Iota', NULL, NULL, NULL, NULL, NULL, '2140 Burdett Ave Troy NY 12180'),
	('Rensselaer Society of Engineers', 'Founded in 1866 as a scientific society, RSE has transitioned through its long history into a social fraternity. We celebrated our 150th anniversary last October, shown on the IFC homepage slideshow is a picture of everyone in attendance. We are currently the second oldest independent fraternity in the United States. Despite the name, all majors are welcome and our brothers span all fields and come from a variety of different backgrounds and places.\n\nSince our birth, RSE has strived for excellence with notable alumni such as George Ferris, inventor of the Ferris wheel, and Washington Roebling, Chief Engineer of the Brooklyn Bridge. Today, we continue this tradition of excellence,one year removed from a 5-star status as well as participating in and raising money for Relay for Life this year. Academics is a focus of ours and we have just begun a new member tutoring program this year to help our incoming brothers adjust to the academic rigor of RPI. Our members are continually placed in top companies such as Boeing, IBM, Regeneron, and Cisco. Matthew Dion, a current PhD candidate, just secured a $100,000 grant to move his start-up company to Germany where he will work to provide affordable, lower-leg prosthetics to developing nations.', 'Local', NULL, NULL, NULL, NULL, NULL, '1501 Sage Ave Troy NY 12180'),
	('Sigma Alpha Epsilon', 'Thinking of going Greek? Check out SAE! Our house is focused on building a strong brotherhood that will make your college experience. We’re all about making the most of your time here socially and academically. Our house is a 19th century mansion located about a mile off campus, and is always accessible via the bus, or any brother.\n\nWe are heavily involved with the RPI community through philanthropy events, fundraisers, and helping out with events on campus, as well as the community of Troy through community service events, community enrichment events, and many more. Academics always come first but that doesn’t mean you can’t have any fun, we like to take full advantage of that whether it be through parties, social mixers with sororities, or just a solid time with the boys, there’s never a boring moment here at SAE. On a national level, SAE is North America’s largest social fraternity with more than 331,000 initiated members and 15,000 undergrads in 317 chapters.', 'NY Epsilon', NULL, NULL, NULL, NULL, NULL, '12 Myrtle Ave Troy NY 12180'),
	('Sigma Chi', 'The Delta Psi chapter of the Sigma Chi Fraternity supports academic excellence, community involvement, leadership development, and lifelong growth of character. Our undergraduate program has produced outstanding alumni, with several being recognized by The International Fraternity for their contributions to Sigma Chi and society, including one president of The International Fraternity, six members of the Order of Constantine, and seven Significant Sigs. Delta Psi is regarded as a leading chapter in Sigma Chi, having won the Peterson Significant Chapter Award the last eight years in a row and being recognized as the fifth overall chapter of Sigma Chi out of 244 active chapters for the last two years. The Delta Psi chapter was also awarded the President''s Cup by Rensselaer in 2012, 2016, and 2017, recognizing Delta Psi''s strength both on campus and in Sigma Chi.\n\nThe goal of Sigma Chi at Rensselaer is to be the premier leadership organization on campus in all facets of our operations. Each year we have brothers involved in nearly all parts of campus, from varsity athletes to student government to music groups. The preferred charity of Sigma Chi is the Huntsman Cancer Institute, for which we have raised over $20,000 for two of the last three years in our annual Derby Days philanthropy event.', 'Delta Psi', NULL, NULL, NULL, NULL, NULL, '58 Pinewoods Ave Troy NY 12180'),
	('Sigma Phi Epsilon', 'Virtue, Diligence, and Brotherly Love. These Cardinal Principles truly define and embody what Sigma Phi Epsilon is all about. SigEp was founded in 1901 at Richmond University under the pretense that “This Fraternity will be different” and came to Rensselaer in 1938.\n\nSigEp strives to create an experience for young men that will transcend life at college and will push for a brighter future. In 2015, SigEp on a national basis voted to abolish the pledging system and replaced it with the Balanced Man Program. This model ameliorates the transition from high school to the real world as it creates an environment where there is constant growth.\n\nAlong with their values, The New York Delta Chapter of SigEp pushes towards servicing and giving back to the community. Every Friday during the school year they host “Bacon, Egg and Cheese” to raise money for Big Brothers Big Sisters, and recently they teamed up with Alpha Gamma Delta and Sole Survivors to host Sexual Assault Awareness Week, a full week of events highlighting the need to speak up and bring awareness to sexual assault. Throughout the years, SigEp has endeavored to transform boys into true Balanced Men that continue to uphold these values and make a difference in the world.', 'NY Delta', NULL, NULL, NULL, NULL, NULL, '2005 15th St Troy NY 12180'),
	('Tau Epsilon Phi', 'We, the brothers of the Epsilon Iota chapter of Tau Epsilon Phi, are excited to take part in RPI''s 2017 Fall Rush. Our brotherhood collectively strives to uphold the ideals of Friendship, Chivalry and Service in every aspect of our professional and personal lives, and we hope to recruit men whom we feel show a similar commitment to and appreciation for these ideals in their own lives as well. We welcome anyone who is interested in rushing or learning more about our brotherhood or campus Greek life to join us at the TEP house during rush. To get to know the people that make up Tau Epsilon Phi, visit our chapter site at tepei.org or come on by!', 'Epsilon Iota', NULL, NULL, NULL, NULL, NULL, '1991 15th St Troy NY 12180'),
	('Tau Kappa Epsilon', 'Originally founded in 1949, and re-founded in 2017, the Gamma-Epsilon Colony of TKE is one of the newest additions to Greek Life at RPI. Having just returned to campus with a new group of 26 men, we are looking forward to making meaningful contributions to the RPI Greek Community.\n\nTKE strives to assist the young men of our fraternity in their mental, physical, and spiritual growth through the ideals of Love, Charity, and Esteem, our core values. As one of the largest fraternities in North America, TKE aims to help our brothers to be upstanding citizens of their communities and society, and contribute to its advancement. Notable Tekes include Ronald Reagan, Howard Schultz, Steve Forbes, Aaron Rodgers, and Terry Bradshaw.\n\nOur brotherhood is composed of men from across the country and all walks of life, including 11 in ROTC programs. We look forward to adding new members who plan to contribute and be integral parts of our budding organization and brotherhood.', 'Gamma Epsilon', NULL, NULL, NULL, NULL, NULL, NULL),
	('Theta Chi', 'Theta Chi has been committed to leading lives of excellence at RPI since 1908.  The motto, “Lead a Helping Hand”, is exemplified through the actions of the Delta Chapter of Theta Chi.\n\nIt isn’t just a house of men. It is a brotherhood. A lifetime bond with the brothers is unlike any other. The web of alumni is tremendous. When you join Theta Chi you have joined a brotherhood with a prestigious group of men.', 'Delta', NULL, NULL, NULL, NULL, NULL, '2100 Burdett Ave Troy NY 12180'),
	('Theta Xi', 'Zoo possesses a culture of excellence in both academics and social environments. We strive to succeed in our majors, and always provide help to brothers who need it. We are deeply involved in other campus activities as well, including engineering honors societies and club sports teams.\n\nWe host several philanthropic events throughout the year as a way to show our appreciation for the campus and surrounding community. One of our signature events is “Dog Days of Finals” where students are invited to pet service dogs to relieve stress. We also do an annual cleanup of the Oakwood Cemetery, and this year hosted a fundraising event with Five Guys Burgers.\n\nOur most important attribute however, is how close we all are with each other. We all share a deep love for this house and each other. On any random afternoon, you can find several of our brothers kicking back in the formal room. If the weather is nice outside, chances are some guys are “Lazy Landing” on our front lawn, soaking up the sun. More often than not, most of us end up eating dinner together after a long day of classes. And of course, we all look forward to our year end camping trip on Lake George. We believe that few houses can form such special bonds as ours. This house for most of us is more than that, it’s a home.', 'Alpha', NULL, NULL, NULL, NULL, NULL, '1490 Sage Ave Troy NY 12180'),
	('Zeta Psi', 'Since 1847, Zeta Psi has built its foundation on a lifelong brotherhood. We are a small, close-knit group that prides ourselves on community service, academics, athletics, and other forms of campus involvement. We are proud to feature members of student government, varsity sports teams, ROTC, and numerous campus wide clubs. All members are motivated to take on house positions which help strengthen organizational, management and leadership skills. Throughout our years at Rensselaer, we build a bond strong enough to last long beyond graduation.', 'Pi', NULL, NULL, NULL, NULL, NULL, '25 Belle Ave Troy NY 12180');


CREATE TABLE events (
	house varchar(50) NOT NULL,
	event_name varchar(50) NOT NULL,
	start_time varchar(10) NOT NULL,
	end_time varchar(10) NOT NULL,
	event_date varchar(10) NOT NULL,
	location varchar(25) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO events(house, event_name, start_time, end_time, event_date, location)
	VALUES
	('Acacia', 'Classes Begin', '08:00', '20:00', '08/31/2017','Campus'),
	('Acacia', 'Meet The Greeks', '16:00', '18:00', '09/01/2017', 'Behind Commons'),
	('Acacia', 'Cookout', '18:00', '20:00', '09/02/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Paintball', '14:00', '16:00', '09/03/2017', NULL),
	('Acacia', 'Tie-dye', '14:00', '16:00', '09/04/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Karaoke Tuesday', '19:00', '21:00', '09/05/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Puppies and Pizza', '18:00', '20:00', '09/06/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Smores & Cocoa', '20:00', '22:00', '09/07/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Friday Fryday', '19:00', '21:00', '09/08/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Laser Tag', '19:00', '22:00', '09/09/2017', NULL),
	('Acacia', 'TASP Service Project', '10:00', '14:00', '09/10/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Smash Bros. Tournament', '20:00', '22:00', '09/11/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Bowling', '19:00', '21:00', '09/12/2017', NULL),
	('Acacia', 'Movie Night', '21:00', '22:30', '09/14/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Leave for Maine Trip', '10:00', '14:00', '09/15/2017', NULL),
	('Acacia', 'Come Back from Maine Trip', '10:00', '14:00', '09/17/2017', NULL),
	('Acacia', 'Bid Delivery Day', '20:00', '22:00', '09/18/2017', NULL),
	('Acacia', 'Bid Dinner', '18:00', '20:00', '09/20/2017', '145 Sunset Terrace Troy NY 12180'),
	('Acacia', 'Bid Signing Day', '12:00', '17:00', '09/22/2017', 'Student Union'),
	('Alpha Epsilon Pi', 'Meet The Greeks', '16:00', '18:00', '09/01/2017', 'Behind Commons'),
	('Alpha Epsilon Pi', 'Saratoga Race Track', '11:00', '16:00', '09/02/2017', 'Saratoga Race Track'),
	('Alpha Epsilon Pi', 'Grafton Cookout', '12:00', '15:00', '09/03/2017', 'Grafton Lake'),
	('Alpha Epsilon Pi', 'Cookout and Sports', '17:00', '19:00', '09/05/2017', '284 Pawling Avenue Troy NY 12180'),
	('Alpha Epsilon Pi', 'Skyzone', '19:00', '21:30', '09/08/2017', 'Skyzone'),
	('Alpha Epsilon Pi', 'Waterfall Hike', '10:00', '15:00', '09/09/2017', NULL),
	('Alpha Epsilon Pi', 'Cookout and Sports', '17:00', '19:00', '09/12/2017', '284 Pawling Avenue Troy NY 12180'),
	('Alpha Epsilon Pi', 'Smoker Poker', '20:30', '22:30', '09/15/2017', '284 Pawling Avenue Troy NY 12180'),
	('Alpha Epsilon Pi', 'Island Campout', '11:00', '12:30', '09/16/2017', 'Lake George'),
	('Alpha Epsilon Pi', 'Island Campout', '11:00', '12:30', '09/17/2017', 'Lake George'),
	('Alpha Epsilon Pi', 'Bid Dinner', '18:00', '22:00', '09/19/2017', '284 Pawling Avenue Troy NY 12180'),
	('Alpha Epsilon Pi', 'Bid Commitment', '12:00', '17:00', '09/22/2017', 'Student Union');


